AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  revalidate-function

  function to revalidate blog content

Resources:
  RevalidateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Timeout: 15
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE 
      Environment:
        Variables:
          REVALIDATE_TOKEN: '{{resolve:ssm:edgarp-website-revalidat-token:1}}'
      Events:
        RunEveryDayAt12AMCronEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 0 * * ? *)

Outputs:
  RevalidateFunctionUrl:
    Value: !GetAtt RevalidateFunctionUrl.FunctionUrl
